In [117]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [118]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.5)

In [119]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9599555061179088

In [120]:
svm = SVC()
svm.fit(X_train, y_train)
print(svm.score(X_test, y_test))

#After some reading I've found that the defaults for SVC have changed over the years from gamma='auto' to gamma='scaled'
#Interestingly enough, the sources I found also claimed I should always scale data for SVM so I'm gonna try that out.

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svm.fit(X_train_scaled, y_train)
print(svm.score(X_test_scaled, y_test))

0.9777530589543938
0.9733036707452726


In [121]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.96440489432703

In [122]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=3)

kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [123]:
for train_index, test_index in kf.split([0, 1, 2, 3, 4, 5, 6, 7, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [124]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [125]:
print(get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test))
print(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
print(get_score(SVC(), X_train, X_test, y_train, y_test))

0.9599555061179088
0.96440489432703
0.9777530589543938


In [126]:
from sklearn.model_selection import StratifiedKFold

In [127]:
sfk = StratifiedKFold(n_splits=3)

In [128]:
scores_lr = []
scores_svm = []
scores_rf = []

for train_index, test_index in sfk.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train, X_test, y_train, y_test))

In [129]:
print(scores_lr)
print(scores_svm)
print(scores_rf)

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]
[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]
[0.9348914858096828, 0.9515859766277128, 0.9298831385642737]


In [130]:
from sklearn.model_selection import cross_val_score

In [133]:
cross_val_score(LogisticRegression(max_iter=10000), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [134]:
cross_val_score(SVC(), digits.data, digits.target)


array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [135]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93333333, 0.91388889, 0.9637883 , 0.96657382, 0.92200557])